# Generated by Django 4.2.7 on 2023-12-31 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
