# Generated by Django 4.2.7 on 2023-12-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_voters_voted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='image',
        ),
        migrations.DeleteModel(
            name='Voters',
        ),
    ]
