# Generated by Django 4.2.7 on 2023-12-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_remove_voters_voted_at_voters_has_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='has_voted',
            new_name='voted',
        ),
    ]
