# Generated by Django 4.2.7 on 2024-01-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_rename_has_voted_voters_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voted_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.voting'),
        ),
    ]
