# Generated by Django 4.2.7 on 2024-01-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_voters_voted_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters',
            name='voted',
        ),
    ]
